import { Rubik } from "next/font/google";
import "./globals.css";


// Componants
import Navbar from "./components/Navbar/Navbar";
import Sidebar from "./components/Sidebar/Sidebar";

import { ReactNode } from "react";
import LayoutWrapper from "./components/LayoutWrapper/LayoutWrapper";
import StoreProvider from "./StoreProvider";

const rubik = Rubik({ subsets: ["latin"] });  // Loading the font which we first imported

export const metadata = {
  title: "TTRPG Editor",
  description: "Generated by Default",
};

export default async function RootLayout({ children }: { children: ReactNode; }) {

  return (
    <html lang="en">
      <body className={rubik.className}>
        <StoreProvider>
          <LayoutWrapper>{children}</LayoutWrapper>
        </StoreProvider>
      </body>
    </html>
  );
}