import { Rubik } from "next/font/google";
import "./globals.css";
import { ReactNode } from "react";
import LayoutWrapper from "./components/LayoutWrapper/LayoutWrapper";
import StoreProvider from "./StoreProvider";
import { Providers } from "./components/SessionProvider";
import { getSession } from "./actions/getCurrentUser";
import Navbar from "./components/Navbar/Navbar";

const rubik = Rubik({ subsets: ["latin"] });  // Loading the font which we first imported

export const metadata = {
  title: "TTRPG Editor",
  description: "Generated by Dejan Bancevic",
  keywords: ["TTRPG", "editor", "Dejan Bancevic", "tabletop", "dnd"],
  authors: [{ name: "Dejan Bancevic" }],
  creator: "Dejan Bancevic",
  applicationName: "TTRPG Editor",
  robots: {
    index: true,
    follow: true,
    nocache: false,
  },
  openGraph: {
    title: "TTRPG Editor",
    description: "The only TTRPG character sheet you'll ever need.",
    url: "https://ttrpg-gamma.vercel.app/",
    siteName: "TTRPG Editor",
    images: [
      {
        url: "https://static1.cbrimages.com/wordpress/wp-content/uploads/2022/08/dnd-5e-dragonlance-chapter-2-art-1.jpg",
        width: 1200,
        height: 630,
      },
    ],
    locale: "en_US",
    type: "website",
  },
};

export default async function RootLayout({ children }: { children: ReactNode; }) {

  const session = await getSession();

  return (
    <html lang="en">
      <body className={rubik.className}>
        <Providers>
          <StoreProvider>
            <LayoutWrapper>
              {session && <Navbar />}
              {children}
            </LayoutWrapper>
          </StoreProvider>
      </Providers>
      </body>
    </html>
  );
}